<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KLPCFEN" failures="0" tests="3" name="com.wolvesres.quanghn.kho.TestValidNhapKho" time="0.005" errors="1" timestamp="2022-04-15T13:46:07 ICT" skipped="0">
  <testcase classname="com.wolvesres.quanghn.kho.TestValidNhapKho" name="testValidNhapKhoSoAmFail" time="0.004">
    <error message="
[public void com.wolvesres.quanghn.kho.TestValidNhapKho.testValidNhapKhoSoAmFail(int,java.lang.Boolean)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testValidNhapKhoSoAmFail([Parameter{index=0, type=int, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Boolean, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer) -12,(java.lang.Integer) 9,(java.lang.Boolean) false]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.wolvesres.quanghn.kho.TestValidNhapKho.testValidNhapKhoSoAmFail(int,java.lang.Boolean)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testValidNhapKhoSoAmFail([Parameter{index=0, type=int, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Boolean, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer) -12,(java.lang.Integer) 9,(java.lang.Boolean) false]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testValidNhapKhoSoAmFail -->
  <system-out/>
  <testcase classname="com.wolvesres.quanghn.kho.TestValidNhapKho" name="testValidNhapKhoSoAmFail" time="0.001"/>
  <system-out/>
  <testcase classname="com.wolvesres.quanghn.kho.TestValidNhapKho" name="testValidNhapKhoSoAmFail" time="0.000"/>
  <system-out/>
</testsuite> <!-- com.wolvesres.quanghn.kho.TestValidNhapKho -->
